### ISSUE TITLE
Scopes for program (.p) vs class (.cls) files

### ISSUE THREAD

**Issue by kenherring** [chriscamicas/abl-tmlanguage#44]
Please excuse my ignorance for TextMate language config...  is it possible to add scopes to differentiate between when we're updating a `.p` vs `.cls`?  Perhaps something like `abl.source.class` and `abl.source.program`.

This would be helpful when defining snippets that we only want for the specific file type.

**Comment by gquerret** [comment]
@PeterJudgeZA Do you know if it's possible or not?

**Comment by PeterJudgeZA** [comment]
While it is possible to add a scope to a whole program, I'm not sure you can have snippets respond to a TextMate scope. 

If you look at https://code.visualstudio.com/docs/editor/userdefinedsnippets it only talks about language, or project or similar scopes.

It may be possible to have a scope for the CLASS ... END CLASS. block but that is somewhat complicated by the ABL's generous syntax (use of colons in particular).

The current grammar has a `fileTypes` property but that needs to be removed (the extensions are part of the extension rather than the grammar).

![grafik](https://github.com/user-attachments/assets/068eea46-bbb9-4df2-9275-27b400806e99)

**Comment by kenherring** [comment]
Closing at it sounds like there's no immediate path forward on this.
